const fs=require('fs'),vm=require('vm');for(const f of ['maplini_connector_core.js','maplini_canvas_core.js','maplini_state_core.js','maplini_reliability_core.js','maplini_export_core.js','maplini_workflow_core.js','maplini_performance_core.js','maplini_mobile_core.js','maplini_selection_core.js','maplini_sync_core.js','maplini_session_core.js','maplini_rc_core.js','maplini_flow_core.js','maplini_access_core.js','maplini_privacy_core.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'));
const W=globalThis.MapliniWorkflowCore,C=globalThis.MapliniCanvasCore,X=globalThis.MapliniExportCore,S=globalThis.MapliniStateCore;function ok(v,m){if(!v)throw new Error(m)}
let p=W.emptyProcess('p-e2e','Order till leverans');const a=C.place(101,99,180,80),b=C.place(502,101,180,80),c=C.place(901,101,180,80);
p=W.addNode(p,{id:'n1',type:'start',text:'Start',x:a.x,y:a.y,w:180,h:80});p=W.addNode(p,{id:'n2',type:'process',text:'Bearbeta order',x:b.x,y:b.y,w:180,h:80});p=W.addNode(p,{id:'n3',type:'end',text:'Levererad',x:c.x,y:c.y,w:180,h:80});
let history=W.pushHistory([],p);p=W.updateNode(p,'n2',{text:'Kontrollera och bearbeta order',background:'#eef6ff',bold:true});p=W.connect(p,'n1','n2','right',{color:'#334155',width:2});p=W.connect(p,'n2','n3','right',{dash:'6 4'});
ok(p.nodes.length===3&&p.links.length===2,'create edit connect');const saved=W.snapshot(p),restored=W.restore(saved);ok(restored.links.length===2,'connectors survive save');
ok(JSON.stringify(restored)===JSON.stringify(S.normalizeProcess(p,p.id)),'roundtrip');ok(X.validateBytes(Uint8Array.from([0x25,0x50,0x44,0x46,1]),'pdf').ok,'pdf');ok(X.validateBytes(Uint8Array.from([0x50,0x4b,0x03,0x04,1]),'zip').ok,'office');
history=W.pushHistory(history,p);p=W.deleteNodes(p,['n2']);ok(p.nodes.length===2&&p.links.length===0,'delete cascade');p=W.undoState(history,p).process;ok(p.nodes.length===3&&p.links.length===2,'undo');
const broken=JSON.parse(JSON.stringify(p));broken.links.push(['n1','missing','right',{}]);ok(S.normalizeProcess(broken,broken.id).links.length===2,'repair orphan');
const plan=X.deletionPlan({currentId:'p-e2e',processes:{'p-e2e':p,'p-other':W.emptyProcess('p-other','Other')}},'p-e2e');ok(plan.deletingCurrent&&plan.nextId==='p-other','fallback');ok(globalThis.MapliniPerformanceCore.signature([p.id,p.nodes.length,p.links.length]).length>0,'performance signature');ok(globalThis.MapliniMobileCore.clientToLocal(100,50,{left:-300,top:0}).x===400,'mobile coordinate');ok(globalThis.MapliniSelectionCore.deleteAction({selectedIds:['n1'],selectedLinkIndices:[0]})==='many','mixed selection');ok(globalThis.MapliniSyncCore.chooseSource({localModifiedAt:2000},{updated_at:new Date(1000).toISOString()})==='local','sync conflict');ok(globalThis.MapliniSessionCore.chooseWorkspace('missing',[]).id===null,'workspace fallback');ok(globalThis.MapliniRcCore.validateStoreInvariant({p:{id:'p'}},'p'),'rc invariant');ok(globalThis.MapliniFlowCore.afterProcessDelete({a:{id:'a'}},'a','a').currentId===null,'delete invariant');ok(!globalThis.MapliniAccessCore.canEdit({sharedView:true,currentRole:'owner'}),'shared readonly');ok(!globalThis.MapliniPrivacyCore.shouldPersistLocally({sharedView:true}),'shared privacy');console.log('critical flow E2E OK');
