const fs=require('fs'),vm=require('vm'),assert=require('assert');
const code=fs.readFileSync(require('path').join(__dirname,'..','maplini_connector_core.js'),'utf8');
vm.runInThisContext(code);
const C=globalThis.MapliniConnectorCore;
assert(C,'connector core missing');
let links=[];
links.push(C.create('n1','n2','right'));
assert.deepStrictEqual(links[0].slice(0,3),['n1','n2','right']);
assert.strictEqual(C.style(links[0]).color,'#687584');
C.setStyle(links,0,{color:'#ff0000',width:4,dash:'dashed'});
assert.strictEqual(C.style(links[0]).color,'#ff0000');
assert.strictEqual(C.style(links[0]).width,4);
assert.strictEqual(C.style(links[0]).dash,'dashed');
C.setVia(links,0,120,220);
assert.strictEqual(C.style(links[0]).viaX,120);
assert.strictEqual(C.style(links[0]).viaY,220);
let serialized=JSON.stringify(links);
let restored=C.normalizeLinks(JSON.parse(serialized));
assert.deepStrictEqual(restored,links);
restored.push(C.create('n2','n3','bottom',{end:'diamond'}));
assert.strictEqual(C.style(restored[1]).end,'diamond');
let remaining=C.removeAt(restored,0);
assert.strictEqual(remaining.length,1);
assert.strictEqual(remaining[0][0],'n2');
assert.strictEqual(C.selectionAfterDelete(1,0),0);
assert.strictEqual(C.selectionAfterDelete(0,0),null);
let bulk=C.removeSelected([C.create('a','b'),C.create('b','c'),C.create('c','d')],new Set(['b']),new Set());
assert.strictEqual(bulk.length,1);
assert.deepStrictEqual(bulk[0].slice(0,2),['c','d']);
let area=C.rectsIntersect({left:0,right:10,top:0,bottom:10},{left:5,right:15,top:5,bottom:15});
assert.strictEqual(area,true);
console.log('connector lifecycle OK');
